version: '3'
services:
  postgres:
    image: "postgres:12.4"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: ubahn-db
  redis:
    image: "redis:6.2"
    ports:
      - "6379:6379"